apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z52yc5rr4-dotnet-basic
  janus-idp.io/tekton: z52yc5rr4-dotnet-basic
  backstage.io/kubernetes-id: z52yc5rr4-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: z52yc5rr4-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
